# Generated by Django 4.2.2 on 2023-06-11 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_task_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="due",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
