# Generated by Django 4.2.2 on 2023-06-11 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="tasks.project",
                verbose_name="parent",
            ),
        ),
    ]
